version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/SmartVotingAppInitializer.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/SecurityWebApplicationInitializer.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/ApplicationConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/MvcConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/WebSecurityConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/AuthenticationProviderConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/SmartVotingController.class'
    - 'ROOT/WEB-INF/lib/aopalliance-1.0.jar'
    - 'ROOT/WEB-INF/lib/commons-fileupload-1.3.3.jar'
    - 'ROOT/WEB-INF/lib/commons-io-2.5.jar'
    - 'ROOT/WEB-INF/lib/commons-logging-1.2.jar'
    - 'ROOT/WEB-INF/lib/javax.servlet-api-3.1.0.jar'
    - 'ROOT/WEB-INF/lib/javax.servlet.jsp-api-2.3.1.jar'
    - 'ROOT/WEB-INF/lib/jstl-1.2.jar'
    - 'ROOT/WEB-INF/lib/spring-aop-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-beans-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-context-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-core-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-expression-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-web-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-webmvc-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-security-web-4.2.3.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-security-core-4.2.3.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-security-config-4.2.3.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-jdbc-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/postgresql-9.4-1206-jdbc42.jar'
    - 'ROOT/WEB-INF/lib/commons-dbcp2-2.1.1.jar'
    - 'ROOT/WEB-INF/lib/commons-pool2-2.4.2.jar'
    - 'ROOT/WEB-INF/views/index.jsp'
    - 'ROOT/WEB-INF/views/login.jsp'
    - 'ROOT/resources/gradients.css'
    - 'ROOT/resources/set-background.js'
    - 'ROOT/resources/styles.css'
    - 'ROOT/resources/tweet.svg'
