version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
      - mv target/ROOT .
artifacts:
  type: zip
  files:
    - 'ROOT/WEB-INF/classes/application.properties'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/SmartVotingAppInitializer.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/SecurityWebApplicationInitializer.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/ApplicationConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/AuthenticationProviderConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/MvcConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/configuration/WebSecurityConfig.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/CategoryController.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/MyPollsController.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/PollController.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/SearchController.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/SmartVotingController.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/controller/UserController.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/CategoryDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/CommentDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/PollDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/PollOptionDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/SignCommentDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/UserDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/dao/VoteDao.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/CategoryRowMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/CommentRowMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/PollOptionRowMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/PollRowMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/SignCommentMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/UserRowMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/mapper/VoteRowMapper.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/Category.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/Comment.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/Poll.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/PollOption.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/SignComment.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/User.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/model/Vote.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/CategoryService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/CommentService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/PollOptionService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/PollService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/SignCommentService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/UserService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/service/VoteService.class'
    - 'ROOT/WEB-INF/classes/com/aws/codestar/projecttemplates/util/TreeNode.class'
    - 'ROOT/WEB-INF/lib/aopalliance-1.0.jar'
    - 'ROOT/WEB-INF/lib/commons-fileupload-1.3.3.jar'
    - 'ROOT/WEB-INF/lib/commons-io-2.5.jar'
    - 'ROOT/WEB-INF/lib/commons-logging-1.2.jar'
    - 'ROOT/WEB-INF/lib/javax.servlet-api-3.1.0.jar'
    - 'ROOT/WEB-INF/lib/javax.servlet.jsp-api-2.3.1.jar'
    - 'ROOT/WEB-INF/lib/jstl-1.2.jar'
    - 'ROOT/WEB-INF/lib/spring-aop-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-beans-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-context-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-core-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-expression-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-web-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-webmvc-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-security-web-4.2.3.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-security-core-4.2.3.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-security-config-4.2.3.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-jdbc-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-tx-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/spring-orm-4.3.14.RELEASE.jar'
    - 'ROOT/WEB-INF/lib/postgresql-9.4-1206-jdbc42.jar'
    - 'ROOT/WEB-INF/lib/commons-dbcp2-2.1.1.jar'
    - 'ROOT/WEB-INF/lib/commons-pool2-2.4.2.jar'
    - 'ROOT/WEB-INF/views/addPollOptions.jsp'
    - 'ROOT/WEB-INF/views/categoryCreateResult.jsp'
    - 'ROOT/WEB-INF/views/createCategory.jsp'
    - 'ROOT/WEB-INF/views/createpoll.jsp'
    - 'ROOT/WEB-INF/views/createUser.jsp'
    - 'ROOT/WEB-INF/views/index.jsp'
    - 'ROOT/WEB-INF/views/login.jsp'
    - 'ROOT/WEB-INF/views/poll.jsp'
    - 'ROOT/WEB-INF/views/searchPolls.jsp'
    - 'ROOT/WEB-INF/views/searchResults.jsp'
    - 'ROOT/WEB-INF/views/userCreateResult.jsp'
    - 'ROOT/WEB-INF/views/viewMyPolls.jsp'
    - 'ROOT/resources/gradients.css'
    - 'ROOT/resources/set-background.js'
    - 'ROOT/resources/styles.css'
    - 'ROOT/resources/tweet.svg'
    - 'ROOT/resources/images/blank-profile-picture.png'
